# Generated by Django 4.0.4 on 2022-05-27 00:07

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edital', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nome_projeto', models.CharField(db_column='NOME_PROJETO', max_length=50)),
                ('inicio_execucao', models.DateField(blank=True, null=True)),
                ('fim_execucao', models.DateField(blank=True, null=True)),
                ('valor_total', models.CharField(blank=True, db_column='VALOR_TOTAL', max_length=20)),
                ('nome_responsavel', models.CharField(blank=True, db_column='NOME_RESPONSAVEL', max_length=50)),
                ('telefone_responsavel', models.CharField(blank=True, db_column='TELEFONE_RESPONSAVEL', max_length=20)),
                ('celular_responsavel', models.CharField(blank=True, db_column='CELULAR_RESPONSAVEL', max_length=20)),
                ('atividades_responsavel', models.TextField(blank=True, db_column='ATIVIDADES_RESPONSAVEL')),
                ('outros_projetos', models.BooleanField(blank=True, db_column='OUTROS_PROJETOS')),
                ('quais_projetos', models.TextField(blank=True, db_column='QUAIS_PROJETOS')),
                ('titulo', models.CharField(blank=True, db_column='TITULO', max_length=50)),
                ('resumo_objetivos', models.TextField(blank=True, db_column='RESUMO_OBJETIVOS')),
                ('apresentacao', models.TextField(blank=True, db_column='APRESENTACAO')),
                ('objetivos', models.TextField(blank=True, db_column='OBJETIVOS')),
                ('abrangencia', models.TextField(blank=True, db_column='ABRANGENCIA')),
                ('justificativa', models.TextField(blank=True, db_column='JUSTIFICATIVA')),
                ('proposta_pedagogica', models.TextField(blank=True, db_column='PROPOSTA_PEDAGOGICA')),
                ('metodologia', models.TextField(blank=True, db_column='METODOLOGIA')),
                ('avaliacao', models.TextField(blank=True, db_column='AVALIACAO')),
                ('publico_beneficiado', models.TextField(blank=True, db_column='PUBLICO_BENEFICIADO')),
                ('acompanhamento_indicadores', models.TextField(blank=True, db_column='ACOMPANHAMENTO_INDICADORES')),
                ('recursos_necessarios', models.TextField(blank=True, db_column='RECURSOS_NECESSARIOS')),
                ('acoes_executadas', models.TextField(blank=True, db_column='ACOES_EXECUTADAS')),
                ('metas_gerais', models.TextField(blank=True, db_column='METAS_GERAIS')),
                ('resultados_esperados', models.TextField(blank=True, db_column='RESULTADOS_ESPERADOS')),
                ('detalhamento_orcamento', models.TextField(blank=True, db_column='DETALHAMENTO_ORCAMENTO')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.perfil', verbose_name='PERFIL')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edital.editalmodel', verbose_name='TEMPLATE')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'db_table': 'PROJETO',
            },
        ),
    ]
