# Generated by Django 4.0.4 on 2022-05-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='fim_execucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='inicio_execucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
