# Generated by Django 4.0.4 on 2022-05-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_projeto_fim_execucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='nome_projeto',
            field=models.CharField(db_column='NOME_PROJETO', max_length=50),
        ),
    ]
