# Generated by Django 4.0.3 on 2022-03-21 23:01

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nome_instituicao', models.CharField(db_column='NOME_INSTITUICAO', max_length=50)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=18)),
                ('logradouro', models.CharField(db_column='LOGRADOURO', max_length=50)),
                ('numero', models.CharField(db_column='NUMERO', max_length=5)),
                ('complemento', models.CharField(db_column='COMPLEMENTO', max_length=100)),
                ('bairro', models.CharField(db_column='BAIRRO', max_length=25)),
                ('cidade', models.CharField(db_column='CIDADE', max_length=30)),
                ('UF', models.CharField(db_column='UF', max_length=2)),
                ('cep', models.CharField(db_column='CEP', max_length=9)),
                ('telefone', models.CharField(db_column='TELEFONE', max_length=13)),
                ('ano_fundacao', models.CharField(db_column='ANO_FUNDACAO', max_length=4)),
                ('total_membros', models.CharField(db_column='TOTAL_MEMBROS', max_length=4)),
                ('nome_presidente', models.CharField(db_column='NOME_PRESIDENTE', max_length=4)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'db_table': 'PERFIL',
            },
        ),
    ]
