# Generated by Django 4.0.3 on 2022-03-29 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_nome_presidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='UF',
            field=models.CharField(choices=[('SC', 'Santa Catarina'), ('PR', 'Parana'), ('RS', 'Gaudérios')], db_column='UF', max_length=2),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(db_column='CNPJ', max_length=14, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.CharField(db_column='NUMERO', max_length=5, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='total_membros',
            field=models.PositiveIntegerField(db_column='TOTAL_MEMBROS'),
        ),
    ]
