# Generated by Django 4.0.3 on 2022-06-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email_instituicao',
            field=models.EmailField(db_column='EMAIL_INSTITUICAO', error_messages={'invalid': 'The Geeks Field you enetered is not unique.'}, max_length=50),
        ),
    ]
