# Generated by Django 4.0.3 on 2022-06-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_email_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email_instituicao',
            field=models.EmailField(db_column='EMAIL_INSTITUICAO', max_length=50),
        ),
    ]
