# Generated by Django 4.0.3 on 2022-06-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_perfil_email_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dirigente',
            field=models.CharField(db_column='DIRIGENTE', max_length=50),
        ),
    ]
