# Generated by Django 4.0.4 on 2022-05-02 23:48

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('edital', models.CharField(db_column='EDITAL', max_length=10)),
                ('texto', models.TextField(db_column='TEXTO', max_length=100)),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'db_table': 'TEMPLATE',
            },
        ),
    ]
